name: CI on Pull Request

on:
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (if you're using Node.js, else skip this step)
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'  # You can adjust the version based on your app

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (assuming you have tests set up)
      - name: Run tests
        run: npm test
