name: Deploy to AWS

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (if you're deploying a Node.js app)
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1' 
